config/routes.rb
Rails.application.routes.draw do
  resources :actors
  resources :movies

  root to: 'pages#home'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_and_belongs_to_many :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_and_belongs_to_many :actors
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :rating)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/actors/_form.html.erb
<%= form_for(actor) do |f| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

  <h1 class="page-title">Actors</h1>
  <%= link_to 'New Actor', new_actor_path, class:'new-link btn btn-secondary' %>

<% @actors.each do |actor| %>
<div class="row actor-row">
  <div class= "col col-sm-1">
  </div>

  <div class= "col col-sm-10">
    
      <div class="card">
        <div class="card-header">
          <h4><%= actor.name.upcase %></h4>
        </div>
        <div class="card-block">
          <h4 class="card-title">Short actor description here</h4>
          
          <p class="card-text">
            Movies:
            <% actor.movies.each do |movie| %>
              <%= movie.title %> |
            <% end %>  
          </p>

          <div class="row">
            <%= link_to 'Show', actor, class:'row-buttons btn btn-primary' %>
            <%= link_to 'Edit', edit_actor_path(actor), class:'row-buttons btn btn-primary' %>
            <%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' }, class:'row-buttons btn btn-primary' %>
          </div>
        </div>
      </div>
    
  </div>

  <div class= "col col-md-1">
  </div>

</div>
<% end %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Name: <%= @actor.name %></li>
    <li class="list-group-item"><%= link_to 'Edit', edit_actor_path(@actor) %></li>
    <li class="list-group-item"><%= link_to 'Back', actors_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="background"></div>
    
    <%= render "shared/application_nav" %>

    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-title">Movies</h1>
<%= link_to 'New Movie', new_movie_path, class:'new-link btn btn-secondary' %>

<% @movies.each do |movie| %>
<div class="row movie-row">
  <div class= "col col-md-1">
  </div>

  <div class= "col col-md-10">
    
      <div class="card">
        <div class="card-header">
          <h4><%= movie.title.upcase %></h4>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= movie.description %></h4>
          
          <p class="card-text">
            Actors:
            <% movie.actors.each do |actor| %>
              <%= actor.name %> |
            <% end %>  
          </p>

          <p class="card-text">
            Genre: <%= movie.genre %>
          </p>

          <p class="card-text">
            Rating: <%= movie.rating %>
          </p>

          <div class="row">
            <%= link_to 'Show', movie, class:'row-buttons btn btn-primary' %>
            <%= link_to 'Edit', edit_movie_path(movie), class:'row-buttons btn btn-primary' %>
            <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class:'row-buttons btn btn-primary' %>
          </div>
        </div>
      </div>
    
  </div>

  <div class= "col col-md-1">
  </div>

</div>
<% end %>

  <br>

  

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Movie: <%= @movie.title %></li>
    <li class="list-group-item">description: <%= @movie.description %></li>
    <li class="list-group-item">Genre: <%= @movie.genre %></li>
    <li class="list-group-item">Rating: <%= @movie.rating %></li>
    <li class="list-group-item"><%= link_to 'Edit', edit_movie_path(@movie) %></li>
    <li class="list-group-item"><%= link_to 'Back', movies_path %></li>
  </ul>
</div>

app/views/pages/home.html.erb
<h1 class="page-title">Home</h1>
<div class="home-card">
  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">I made separate Movie and Actors tables and set up a has_and_belongs_to_many relationship between the two.</li>
      <li class="list-group-item">This made sense to me because movies have many actors and actors have many movies.</li>
      <li class="list-group-item">I have example data in the seeds file that can be used to seed the database.</li>
      <li class="list-group-item">Actors and movies can be added, edited and deleted, but associations can only be set in rails console so far.</li>
      <li class="list-group-item"><a href="http://www.josh-mcdonald.com">My website</a></li>
    </ul>
  </div>
<div>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to "Home", root_path, class:'navbar-brand' %>
  
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Movies", movies_path, class:'nav-item nav-link' %>
      <%= link_to "Actors", actors_path, class:'nav-item nav-link' %>
    </div>
  </div>
</nav>